# Generated by Django 6.1.1 on 2026-09-24 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='core.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('status', 'user'), name='status_mention_unique')],
            },
        ),
    ]
