# Generated by Django 6.1.1 on 2026-09-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='action',
            field=models.CharField(blank=True, choices=[('dismiss', 'Dismissed'), ('delete_status', 'Deleted the post')], default='', max_length=20),
        ),
    ]
