# Generated by Django 6.1.1 on 2026-09-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_report_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='action',
            field=models.CharField(blank=True, choices=[('dismiss', 'Dismissed'), ('delete_status', 'Deleted the post'), ('suspend', 'Suspended the account')], default='', max_length=20),
        ),
    ]
