# Generated by Django 6.1.1 on 2026-09-29 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_alter_report_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_blocks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
