# Generated by Django 6.1.1 on 2026-10-06 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_status_status_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('raw_description', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('local', models.BooleanField(default=True)),
                ('origin_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remote_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remote_url', models.TextField(blank=True, default='')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='film_list', to='core.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_items', to='core.film')),
                ('film_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.filmlist')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('film_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='lists.filmlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='filmlist',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_url__gt', '')), fields=('remote_url',), name='unique_remote_url_for_list_mirrors'),
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.UniqueConstraint(fields=('film_list', 'film'), name='one_row_per_film_per_list'),
        ),
        migrations.AddConstraint(
            model_name='listsave',
            constraint=models.UniqueConstraint(fields=('user', 'film_list'), name='one_save_per_user_per_list'),
        ),
    ]
