# Generated by Django 6.1.1 on 2026-10-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listsave',
            name='notice_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
