# Generated by Django 6.1.1 on 2026-09-06 17:05

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sort_title', models.CharField(db_index=True, editable=False, max_length=512)),
                ('subtitle', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='Runtime in minutes.', null=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list)),
                ('directors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list)),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('tmdb_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('origin_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remote_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_title', 'year'],
            },
        ),
        migrations.CreateModel(
            name='MergedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.PositiveBigIntegerField(unique=True)),
                ('new_id', models.PositiveBigIntegerField()),
                ('merged_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'merged films',
            },
        ),
    ]
