# Generated by Django 6.1.1 on 2026-09-06 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_film_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('origin_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remote_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShelfFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.film')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'shelf films',
            },
        ),
        migrations.AddField(
            model_name='shelf',
            name='films',
            field=models.ManyToManyField(related_name='shelves', through='core.ShelfFilm', through_fields=('shelf', 'film'), to='core.film'),
        ),
        migrations.AddConstraint(
            model_name='shelffilm',
            constraint=models.UniqueConstraint(fields=('film', 'shelf'), name='unique_film_per_shelf'),
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('user', 'identifier'), name='unique_shelf_identifier_per_user'),
        ),
    ]
