# Generated by Django 6.1.1 on 2026-09-07 03:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shelf_shelffilm_shelf_films_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(blank=True, choices=[('comment', 'Comment'), ('review', 'Review'), ('review_rating', 'Rating-only review')], max_length=20, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('raw_content', models.TextField(blank=True, default='')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('published_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('local', models.BooleanField(default=True)),
                ('origin_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remote_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='core.film')),
                ('reply_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='core.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False), ('status_type__in', ['review', 'review_rating'])), fields=('user', 'film'), name='unique_review_per_user_per_film')],
            },
        ),
    ]
