# Generated by Django 6.1.1 on 2026-09-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='raw_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
