# Generated by Django 6.1.1 on 2026-09-12 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_origin_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='remote_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='status',
            name='remote_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_url__gt', '')), fields=('remote_url',), name='unique_remote_url_for_film_mirrors'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_url__gt', '')), fields=('remote_url',), name='unique_remote_url_for_status_mirrors'),
        ),
    ]
