# Generated by Django 6.1.1 on 2026-09-22 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_film_remote_url_status_remote_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('origin_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'status'), name='unique_like_per_user_per_status')],
            },
        ),
    ]
