# Generated by Django 6.1.1 on 2026-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(blank=True, choices=[('comment', 'Comment'), ('review', 'Review'), ('review_rating', 'Rating-only review'), ('list', 'List')], max_length=20, null=True),
        ),
    ]
