# Generated by Django 6.1.1 on 2026-09-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('reply', 'Reply'), ('mention', 'Mention')], max_length=20),
        ),
    ]
