# Generated by Django 6.1.1 on 2026-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ReelTalk', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('signup_policy', models.CharField(choices=[('open', 'Open'), ('invite', 'Invite-only')], default='open', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
