# Generated by Django 6.1.1 on 2026-09-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_linkdomain_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
