# Generated by Django 6.1.1 on 2026-09-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_backfill_user_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="actor_url",
            field=models.TextField(blank=True, default=""),
        ),
        # Remote mirrors are stored as <preferredUsername>@<netloc>; local
        # accounts can never contain '@' (R12), so the namespaces are disjoint
        # and one mirror per home actor URL is enough to keep them unique.
        migrations.AlterField(
            model_name="user",
            name="localname",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("local", False)),
                fields=("actor_url",),
                name="unique_actor_url_for_remote_mirrors",
            ),
        ),
    ]
