# Generated by Django 6.1.1 on 2026-09-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_user_actor_url_alter_user_localname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inbox_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
