# Generated by Django 6.1.1 on 2026-09-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_user_inbox_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
