# Generated by Django 6.1.1 on 2026-09-24 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_sitesettings_invite_scope_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_last_read',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
