# Generated by Django 6.1.1 on 2026-09-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_user_notifications_last_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Designates a site moderator. Independent of staff status: a moderator can moderate /moderate/ and cannot open the admin.'),
        ),
    ]
