# Generated by Django 6.1.1 on 2026-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_origin',
            field=models.CharField(blank=True, choices=[('local', 'Suspended by this instance')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
