# Generated by Django 6.1.1 on 2026-09-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_user_suspended_at_user_suspension_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
