# Generated by Django 6.1.1 on 2026-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_user_ban_reason_user_banned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suspension_origin',
            field=models.CharField(blank=True, choices=[('local', 'Suspended by this instance'), ('domain_block', 'Suspended by a domain block')], default='', max_length=16),
        ),
    ]
