# Generated by Django 6.1.1 on 2026-09-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_user_suspension_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_email',
            field=models.BooleanField(default=True, help_text='Email this account when a new report is filed. Set by the site admin beside the moderator grant; has no effect unless an email address is on file.'),
        ),
    ]
