# Generated by Django 6.1.1 on 2026-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_emailverificationtoken_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='send_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
