# Generated by Django 6.1.1 on 2026-09-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_emailverificationtoken_send_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='request_ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
